// This file was generated by iSukces.Templates ver 1.24.1229.5
// Get latest version from https://raw.githubusercontent.com/isukces/iSukces.Templates/main/Code/iSukces.Templates/PrimitiveObsession.ttinclude

#nullable enable
using System;

namespace iSukces.Code.VsSolutions;

public readonly partial struct CsLangVersion: IEquatable<CsLangVersion>
{
    public CsLangVersion(string? value) => _value = value?.Trim();

    public override bool Equals(object? obj) => obj is CsLangVersion x && Equals(x);

    public bool Equals(CsLangVersion other) => Comparer.Equals(Value, other.Value);

    public override int GetHashCode() => Comparer.GetHashCode(Value);

    public static implicit operator CsLangVersion(string? value) => new CsLangVersion(value);

    public static implicit operator string(CsLangVersion value) => value.Value;

    public static bool operator ==(CsLangVersion left, CsLangVersion right) => left.Equals(right);

    public static bool operator !=(CsLangVersion left, CsLangVersion right) => !left.Equals(right);

    private readonly string? _value;

    public string Value => _value ?? string.Empty;

    public static CsLangVersion Empty { get; } = new CsLangVersion(null);

    public bool IsEmpty => string.IsNullOrEmpty(_value);

    public static StringComparer Comparer => StringComparer.Ordinal;

}



